org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Project Info
baseVersion = 3.0.0
maven_group = net.rasanovum
modId = timber_frames
slug = timber_frames
user = RasaNovum

# Metadata
mod.name = Timber Frames
mod.id = timber_frames
mod.description = Timber Frames adds various timber frame blocks and a tool to customize the shape of the frames using a connective texture system.
mod.authors = Rasa Novum
mod.contributors = xameryn, science_bird
mod.version = 3.0.0
mod.license = RSL-1.0
mod.homepage = https://github.com/Rasa-Novum/Timber_Frames
mod.issues = https://github.com/Rasa-Novum/Timber_Frames/issues
mod.sources = https://github.com/Rasa-Novum/Timber_Frames

# Publishing
publish.modrinth = M7N4aD7O
publish.curseforge = 606011

# Dependency Versions
deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.loader=[VERSIONED]
deps.fabric_loader=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.rosetta=0.1.1
deps.runeweaver=[VERSIONED]
deps.iris=[VERSIONED]
