modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
description = '''${modDescription}'''
authors = "${authors}"
credits = "${contributors}"
displayURL = "${homepage}"
logoFile = "logo.png"

[[mixins]]
config = "timber_frames.mixins.json"

[[dependencies.${ modId }]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
type = "required"
versionRange = "[${mc},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "rosetta_library"
type = "required"
versionRange = "[${rosetta},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "runeweaver"
type = "required"
versionRange = "[${runeweaver},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "runeweaver_rosetta"
type = "required"
versionRange = "[${runeweaver},)"
ordering = "NONE"
side = "BOTH"
